# Generated by Django 4.0.5 on 2022-07-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=30, verbose_name='Producto')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion Producto')),
                ('precio', models.FloatField(verbose_name='Precio $')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Suscriptores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre Suscriptor')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido Suscriptor')),
                ('edad', models.SmallIntegerField(verbose_name='Edad')),
                ('fechanacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
        ),
    ]
