# Generated by Django 4.0.5 on 2022-07-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOliveto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre Seguidor')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido Seguidor')),
                ('edad', models.SmallIntegerField(verbose_name='Edad')),
                ('fechanacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
        ),
        migrations.DeleteModel(
            name='Suscriptores',
        ),
    ]
