# Generated by Django 4.0.5 on 2022-07-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOliveto', '0004_remove_seguidores_fechanacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre Contacto')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido Contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
