# Generated by Django 4.0.5 on 2022-07-25 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOliveto', '0007_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
